version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: fita-a-fita
        ports:
            - 27017:27017
        volumes:
            - mongo-data:/data/db
            - ./apps/fita-a-fita-backend/docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
    mongo-data: # name of the volume
        driver: local # driver of the volume
        external: false # if the volume is external
